# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17676ec9bcc6b731cdc88e7249e5a12fc07540a65521ee05f624d3e4b330c7026cab59414fc1b8ad502dc3c7435ff1b50c206a579739e8eb186f034f5f5affb9

test:
  secret_key_base: 9fddae04507c8b1c84dba5eb3d25a60b48dcb0c3b7f406ae5f5bc71b87cf9044096fdbc3cd5124eb57006b8e6eaf5511af327609aa36408f73781800e2841ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
